# Set leader key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Reload 
bind-key r source-file ~/.tmux.conf

# Vim-tmux-navigator
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Start index of window/pane with 1
set -g base-index 1
setw -g pane-base-index 1
set-window-option -g pane-base-index 1
set-window-option -g renumber-windows on

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Theme
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark256'
set -g @tmux-gruvbox-statusbar-alpha 'false'
set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'catppuccin'

set -g @tmux2k-uptime-colors "gray white"

set -g @tmux2k-left-plugins "session git cpu ram"
set -g @tmux2k-right-plugins "uptime time"

set -g @tmux2k-window-colors "gray white"

# Clean plugins
run '~/.tmux/plugins/tpm/scripts/clean_plugins.sh'

run '~/.tmux/plugins/tpm/tpm'
